-keep class com.google.android.gms.internal.** { *; }
-keep class com.google.firebase.auth.** { *; }
-keep class com.google.firebase.app.** { *; }
-keep class com.firebase.ui.auth.** { *; }
-keep class com.google.identitytoolkit.** { *; }
